language: java

jdk:
  - oraclejdk8

sudo:
  - required

os:
  - linux

services:
  - docker
  - mongodb

before_install:
  - . ./.ci/prepare-travis.sh
  - openssl aes-256-cbc -pass pass:$PGP_KEY_PASSWORD -in .ci/secring.gpg.enc -out ~/secring.gpg -d

before_script:
  - rm nitrite-datagate/src/main/resources/application.properties

script:
  - travis_retry . ./.ci/build.sh

after_success:
  - travis_retry . ./.ci/release.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file:
    - $TRAVIS_BUILD_DIR/nitrite-datagate/src/main/dist/nitrite-datagate-$NITRITE_VERSION.zip
    - $TRAVIS_BUILD_DIR/nitrite-explorer/build/libs/nitrite-explorer-$NITRITE_VERSION.jar
  on:
    tags: true

env:
  global:
    - NITRITE_VERSION=1.0
    - PGP_KEY_FILE=~/secring.gpg
